name: Update dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/**
    tags:
      - 'v*'

env:
  REGISTORY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-depoy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        id: check_out
        uses: actions/checkout@v5
  
      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: type=semver,pattern={{version}}
  
      - name: Docker login
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
  
      - name: Update deployment manifest and push
        id: update_manifest
        run: |
          cd ./manifest/overlays/dev
          sed -i "s|image: ${{ env.IMAGE }}:.*|image: ${{ env.IMAGE }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}|" deployment-patch.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to v${{ env.DOCKER_METADATA_OUTPUT_VERSION }}"
          git push origin main
